-- MySQL Script generated by MySQL Workbench
-- Mon Jul 18 18:28:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cardhub_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cardhub_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardhub_db` DEFAULT CHARACTER SET utf8 ;
USE `cardhub_db` ;

-- -----------------------------------------------------
-- Table `cardhub_db`.`system_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardhub_db`.`system_codes` (
  `idsystem_codes` INT NOT NULL AUTO_INCREMENT,
  `system_code` VARCHAR(40) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  PRIMARY KEY (`idsystem_codes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardhub_db`.`system_shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardhub_db`.`system_shops` (
  `idsystem_shops` INT NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(45) NOT NULL,
  `shop_logo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsystem_shops`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardhub_db`.`system_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardhub_db`.`system_countries` (
  `idsystem_countries` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsystem_countries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardhub_db`.`system_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardhub_db`.`system_cards` (
  `idsystem_cards` INT NOT NULL AUTO_INCREMENT,
  `card_uid` VARCHAR(150) NOT NULL,
  `card_name` VARCHAR(250) NOT NULL,
  `card_image64` LONGTEXT NOT NULL,
  `system_code` INT NOT NULL,
  `system_shop` INT NOT NULL,
  `system_country` INT NOT NULL,
  PRIMARY KEY (`idsystem_cards`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardhub_db`.`system_code_limit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardhub_db`.`system_code_limit` (
  `idsystem_code_limit` INT NULL AUTO_INCREMENT,
  `max_users` INT NOT NULL,
  `system_code` INT NOT NULL,
  PRIMARY KEY (`idsystem_code_limit`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
